migrationEnable: "true"

# Migration Start Version
currentVersion: "2.0.0"
# Migration End Version
migrateVersion: "3.0.0"

continueOnError: "false"
batchUpdate: "true"
ignoreForInactiveTenants: "true"

migrateTenantRange: "false"
migrationStartingTenantID: "0"
migrationEndingTenantID: "0"

dataSource: "jdbc/WSO2OB_DB"

versions:
 -
  version: "2.0.0"
  migratorConfigs:
   -
    name: "ConsentMigrator"
    spec: "UK"
    order: 1
    parameters:
      location: "step1"
      schema: "ob"
  -
    name: "DCRMigrator"
    spec: "UK"
    order: 1
    parameters:
      location: "step2"
      schema: "ob"
