# ------------------------------------------------------------------------
#
# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 Inc. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein is strictly forbidden, unless permitted by WSO2 in accordance with
# the WSO2 Commercial License available at http://wso2.com/licenses. For specific
# language governing the permissions and limitations under this license,
# please see the license as well as any agreement you’ve entered into with
# WSO2 governing the purchase of this software and any associated services.
#
# ------------------------------------------------------------------------

migrationEnable: "true"

# Migration Start Version
currentVersion: "2.0.0"
# Migration End Version
migrateVersion: "3.0.0"

batchUpdate: "true"

dataSource: "jdbc/WSO2OB_DB"

versions:
  -
    version: "2.0.0"
    migratorConfigs:
      -
        name: "ConsentMigrator"
        spec: "UK"
        order: 1
        parameters:
          schema: "ob"
      -
        name: "DCRMigrator"
        spec: "UK"
        order: 2
        parameters:
          schema: "ob"